version: '2'
services:
  web:
    restart: always
    build: .
    container_name: landscapes
    ports:
     - "3000:3000"
     - "5858:5858"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    volumes_from:
     - web-data
  web-data:
    build: .
    container_name: landscapes-data
    entrypoint: /bin/true
    volumes:
     - ./:/opt/mean.js
     - /opt/mean.js/node_modules
     - /opt/mean.js/public
     - /opt/mean.js/uploads
  db:
    image: mongo:3.2
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.2
    container_name: mongo-data
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true

  # https://github.com/osixia/docker-openldap
  openldap:
    image: osixia/openldap
    container_name: openldap
    environment:
        LDAP_ORGANISATION: "andscapes.io"
        LDAP_DOMAIN: "landscapes.io"
        LDAP_BASE_DN: "dc=landscapes,dc=io"
        LDAP_ADMIN_PASSWORD: "admin"
     
  # https://github.com/osixia/docker-phpLDAPadmin
  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      # PHPLDAPADMIN_HTTPS=false:
    links:
      - openldap
    ports:
      - "8080:80"
      - "8443:443"
