# https://github.com/osixia/docker-openldap
# Expose default ldap & ldaps ports --> 389 636
openldap:
  image: osixia/openldap
  container_name: openldap
  environment:
    LDAP_ORGANISATION: "Landscapes"
    LDAP_DOMAIN: "landscapes.io"
    LDAP_BASE_DN: "dc=landscapes,dc=io"
    LDAP_ADMIN_PASSWORD: "admin"
  ports:
    - "389:389"
    - "636:636"
     
# https://github.com/osixia/docker-phpLDAPadmin
phpldapadmin:
  image: osixia/phpldapadmin
  container_name: phpldapadmin
  environment:
    PHPLDAPADMIN_LDAP_HOSTS: openldap
    # PHPLDAPADMIN_HTTPS=false:
  links:
    - openldap
  ports:
    - "8080:80"
    - "8443:443"

# https://localhost:8443
# cn=admin,dc=landscapes,dc=io
